In [25]:
import objax
import jax.numpy as jn

class Linear(objax.Module):
    def __init__(self, m, n):
        self.w = objax.TrainVar(objax.random.normal((m, n)))
        self.b = objax.TrainVar(jn.zeros(n))
        self.x = objax.StateVar(jn.array(0))
    def __call__(self, x):
        self.x.value = -self.b.value.sum()+1
        return x.dot(self.w.value) + self.b.value

In [26]:
L = Linear(3,4)

In [27]:
def loss():
    y = L(jn.zeros(3))
    return L.x.value

In [28]:
objax.Grad(loss,L.vars())()

[array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32),
 DeviceArray([-1., -1., -1., -1.], dtype=float32)]

In [26]:
L.vars()

{'(Linear).w': <objax.variable.TrainVar at 0x7f941017fa90>,
 '(Linear).b': <objax.variable.TrainVar at 0x7f941017ff10>,
 '(Linear).x': <objax.variable.StateVar at 0x7f941017fc40>}

In [5]:
x = objax.StateVar(jn.zeros(3))

In [7]:
y = objax.TrainVar(jn.zeros(3))

In [9]:
(x.value+y.value)

DeviceArray([0., 0., 0.], dtype=float32)

In [10]:
gv = objax.GradValues(lambda : (x.value+y.value), x.vars()+y.vars())

AttributeError: 'StateVar' object has no attribute 'vars'

In [27]:
objax.StateVar(0)

In [5]:
jn.zeros(1)

DeviceArray([0.], dtype=float32)